/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { PrescriptionRegistry } from "./PrescriptionRegistry";
export * as factories from "./factories";
export { PrescriptionRegistry__factory } from "./factories/PrescriptionRegistry__factory";
